name: Deploy to EC2 Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into Server and Update app.properties
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 600s
          script: |
            echo "Updating app.properties on the server..."
            echo "db.server=${{ secrets.DB_SERVER }}" > /test/backend/config/app.properties
            echo "db.name=${{ secrets.DB_NAME }}" >> /test/backend/config/app.properties
            echo "db.user=${{ secrets.DB_USER }}" >> /test/backend/config/app.properties
            echo "db.password=${{ secrets.DB_PASSWORD }}" >> /test/backend/config/app.properties
            echo "db.port=${{ secrets.DB_PORT }}" >> /test/backend/config/app.properties
            echo "db.connectionLimit=${{ secrets.DB_CONNECTION_LIMIT }}" >> /test/backend/config/app.properties
            # Add other credentials if needed
            echo "Update completed."


           

