name: Deploy to Test Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into Server and Transfer app.properties
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Updating app.properties on the server..."
            echo "db.server=${{ secrets.DB_SERVER }}" > /path/on/server/app.properties
            echo "db.name=${{ secrets.DB_NAME }}" >> /path/on/server/app.properties
            echo "db.user=${{ secrets.DB_USER }}" >> /path/on/server/app.properties
            echo "db.password=${{ secrets.DB_PASSWORD }}" >> /path/on/server/app.properties
            echo "db.port=${{ secrets.DB_PORT }}" >> /path/on/server/app.properties
            echo "db.connectionLimit=${{ secrets.DB_CONNECTION_LIMIT }}" >> /path/on/server/app.properties
            # Add other credentials if needed
      - name: SSH into Server and Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Restarting the server..."
            # Add commands to restart your server


