name: Deploy to EC2 Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into Server and Update app.properties
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Updating app.properties on the server..."

            # Print values into another file
            echo "db.server=${{ secrets.DB_SERVER }}" > /test/backend/config/temp_properties
            echo "db.name=${{ secrets.DB_NAME }}" >> /test/backend/config/temp_properties
            echo "db.user=${{ secrets.DB_USER }}" >> /test/backend/config/temp_properties
            echo "db.password=${{ secrets.DB_PASSWORD }}" >> /test/backend/config/temp_properties
            echo "db.port=${{ secrets.DB_PORT }}" >> /test/backend/config/temp_properties
            echo "db.connectionLimit=${{ secrets.DB_CONNECTION_LIMIT }}" >> /test/backend/config/temp_properties

            # Append the result to the app.properties file
            cat /test/backend/config/temp_properties.txt >> /test/backend/config/app.properties

            # Log the updated properties for verification
            cat /test/backend/config/app.properties

            echo "Update completed"

           

